import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { SupabasePtoSetting, SupabaseTeacherProfile } from "@/lib/supabaseLeave";

export default function PtoSettingsPanel({ academicYear, teachers, settings, canEdit, onSave, onAction }: { academicYear: string; teachers: SupabaseTeacherProfile[]; settings: SupabasePtoSetting[]; canEdit: boolean; onSave: (teacherId: string, totalDays: number) => Promise<void>; onAction: (message: string) => void }) {
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const valueFor = (teacherId: string) => drafts[teacherId] ?? String(settings.find((setting) => setting.teacher_id === teacherId)?.total_days ?? "");
  return <Card className="border-0 bg-white/90 shadow-[0_18px_45px_rgba(81,73,58,0.08)]"><CardHeader><CardTitle className="text-lg">特休額度設定 · PTO annual limits</CardTitle><p className="text-sm text-[#92978f]">為每位外師設定 {academicYear} 年度特休總天數，病假、事假與公假不在此設定。</p></CardHeader><CardContent className="space-y-3">{teachers.length === 0 ? <p className="rounded-xl bg-[#faf9f5] p-4 text-sm text-[#92978f]">目前尚未找到外師帳號 · No teacher profiles found.</p> : teachers.map((teacher) => <div key={teacher.user_id} className="flex flex-col gap-3 rounded-2xl border border-[#eeeae1] bg-[#fcfbf8] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-[#405049]">{teacher.name || teacher.email || teacher.user_id}</p><p className="mt-1 text-xs text-[#92978f]">{teacher.email}</p></div><div className="flex items-center gap-2"><Input aria-label={`${teacher.email ?? teacher.user_id} PTO days`} type="number" min="0" step="0.5" disabled={!canEdit} value={valueFor(teacher.user_id)} onChange={(event) => setDrafts((current) => ({ ...current, [teacher.user_id]: event.target.value }))} className="h-10 w-28 bg-white" /><span className="text-sm text-[#718076]">日</span>{canEdit && <Button type="button" size="sm" className="rounded-xl bg-[#304b3b] hover:bg-[#41644f]" onClick={async () => { const totalDays = Number(valueFor(teacher.user_id)); if (!Number.isFinite(totalDays) || totalDays < 0) { onAction("PTO 天數必須是 0 或以上 · Enter a valid PTO limit"); return; } try { await onSave(teacher.user_id, totalDays); onAction("PTO 額度已儲存 · PTO limit saved"); } catch (error) { onAction(error instanceof Error ? error.message : "Unable to save PTO setting"); } }}>儲存</Button>}</div></div>)}</CardContent></Card>;
}
