-- Foreign Teacher Leave Management System
-- Supabase PostgreSQL migration. Apply with `supabase db push` after review.

create extension if not exists pgcrypto;

create type public.app_role as enum ('teacher', 'cingshan', 'dongyuan', 'admin');
create type public.leave_type as enum ('PTO', 'Sick Leave', 'Personal Leave', 'Official Leave', 'Make-up Leave');
create type public.leave_status as enum ('Pending', 'Approved', 'Rejected');
create type public.approval_decision as enum ('Approved', 'Rejected');
create type public.notification_recipient as enum ('SchoolMailbox', 'Teacher');
create type public.notification_event as enum ('Submitted', 'Approved', 'Rejected');
create type public.notification_status as enum ('Queued', 'Sent', 'Failed');

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  line_user_id text unique,
  role public.app_role not null default 'teacher',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(user_id, name, email, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email), new.email,
    case when new.raw_app_meta_data->>'role' in ('teacher','cingshan','dongyuan','admin')
      then (new.raw_app_meta_data->>'role')::public.app_role else 'teacher'::public.app_role end)
  on conflict (user_id) do update set email = excluded.email, name = excluded.name;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users for each row execute procedure public.handle_new_user();

create table public.school_calendar_settings (
  id bigint generated by default as identity primary key,
  academic_year text not null unique,
  contract_start date not null,
  contract_end date not null,
  summer_start date not null,
  summer_end date not null,
  winter_start date not null,
  winter_end date not null,
  updated_by uuid not null references auth.users(id),
  updated_at timestamptz not null default now(),
  check (contract_start <= contract_end),
  check (summer_start <= summer_end),
  check (winter_start <= winter_end)
);

create table public.makeup_days (
  id bigint generated by default as identity primary key,
  academic_year text not null,
  makeup_date date not null,
  source_date date,
  assigned_school text not null check (assigned_school in ('青山國小', '東原國中')),
  note text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (academic_year, makeup_date)
);

create table public.leave_applications (
  id bigint generated by default as identity primary key,
  application_no text not null unique,
  teacher_id uuid not null references auth.users(id),
  leave_type public.leave_type not null,
  reason text not null,
  official_document_no text,
  official_location text,
  start_at timestamptz not null,
  end_at timestamptz not null,
  total_hours numeric(8,2) not null check (total_hours > 0),
  status public.leave_status not null default 'Pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (start_at <= end_at)
);

create table public.leave_days (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.leave_applications(id) on delete cascade,
  leave_date date not null,
  hours numeric(8,2) not null check (hours > 0),
  assigned_school text not null check (assigned_school in ('青山國小', '東原國中')),
  route_reason text not null
);

create table public.leave_balances (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references auth.users(id) on delete cascade,
  academic_year text not null,
  leave_type public.leave_type not null,
  total_hours numeric(8,2) not null default 0 check (total_hours >= 0),
  approved_used_hours numeric(8,2) not null default 0 check (approved_used_hours >= 0),
  updated_at timestamptz not null default now(),
  unique (teacher_id, academic_year, leave_type)
);

create table public.leave_attachments (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.leave_applications(id) on delete cascade,
  file_name text not null,
  mime_type text not null,
  storage_key text not null unique,
  uploaded_at timestamptz not null default now()
);

create table public.leave_approvals (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.leave_applications(id) on delete cascade,
  school text not null check (school in ('青山國小', '東原國中')),
  approver_id uuid not null references auth.users(id),
  decision public.approval_decision not null,
  note text,
  decided_at timestamptz not null default now()
);

create table public.leave_routing_events (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.leave_applications(id) on delete cascade,
  source_date date not null,
  assigned_school text not null check (assigned_school in ('青山國小', '東原國中')),
  rule text not null,
  created_at timestamptz not null default now()
);

create table public.leave_notifications (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.leave_applications(id) on delete cascade,
  recipient_type public.notification_recipient not null,
  recipient_ref text not null,
  event_type public.notification_event not null,
  channel text not null default 'LINE' check (channel = 'LINE'),
  status public.notification_status not null default 'Queued',
  error_message text,
  line_message_id text,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.line_webhook_events (
  id bigint generated by default as identity primary key,
  webhook_event_id text not null unique,
  event_type text not null,
  line_user_id text,
  line_group_id text,
  payload jsonb not null,
  received_at timestamptz not null default now()
);

create index leave_days_application_idx on public.leave_days(application_id);
create index leave_attachments_application_idx on public.leave_attachments(application_id);
create index leave_notifications_status_idx on public.leave_notifications(status, created_at);

create or replace function public.current_role()
returns public.app_role language sql stable security definer set search_path = public as $$
  select coalesce((select role from public.profiles where user_id = auth.uid()), 'teacher'::public.app_role);
$$;

create or replace function public.can_access_application(application_id_input bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.leave_applications a
    where a.id = application_id_input
      and (a.teacher_id = auth.uid() or public.current_role() in ('cingshan','dongyuan','admin'))
  );
$$;

create or replace function public.can_review_school(school_input text)
returns boolean language sql stable security definer set search_path = public as $$
  select public.current_role() = 'admin'
    or (public.current_role() = 'cingshan' and school_input = '青山國小')
    or (public.current_role() = 'dongyuan' and school_input = '東原國中');
$$;

alter table public.profiles enable row level security;
alter table public.school_calendar_settings enable row level security;
alter table public.makeup_days enable row level security;
alter table public.leave_applications enable row level security;
alter table public.leave_days enable row level security;
alter table public.leave_balances enable row level security;
alter table public.leave_attachments enable row level security;
alter table public.leave_approvals enable row level security;
alter table public.leave_routing_events enable row level security;
alter table public.leave_notifications enable row level security;
alter table public.line_webhook_events enable row level security;

create policy profiles_self_read on public.profiles for select to authenticated using (user_id = auth.uid());
create policy profiles_admin_manage on public.profiles for all to authenticated using (public.current_role() = 'admin') with check (public.current_role() = 'admin');
create policy calendar_read_authenticated on public.school_calendar_settings for select to authenticated using (true);
create policy calendar_primary_manage on public.school_calendar_settings for all to authenticated using (public.current_role() in ('cingshan','admin')) with check (public.current_role() in ('cingshan','admin'));
create policy makeup_read_authenticated on public.makeup_days for select to authenticated using (true);
create policy makeup_primary_manage on public.makeup_days for all to authenticated using (public.current_role() in ('cingshan','admin')) with check (public.current_role() in ('cingshan','admin'));
create policy applications_read_authorized on public.leave_applications for select to authenticated using (teacher_id = auth.uid() or public.current_role() in ('cingshan','dongyuan','admin'));
create policy applications_teacher_insert on public.leave_applications for insert to authenticated with check (teacher_id = auth.uid() and public.current_role() in ('teacher','admin'));
create policy applications_admin_update on public.leave_applications for update to authenticated using (public.current_role() in ('admin','cingshan','dongyuan')) with check (public.current_role() in ('admin','cingshan','dongyuan'));
create policy days_read_authorized on public.leave_days for select to authenticated using (public.can_access_application(application_id));
create policy days_insert_owner on public.leave_days for insert to authenticated with check (public.can_access_application(application_id));
create policy balances_read_authorized on public.leave_balances for select to authenticated using (teacher_id = auth.uid() or public.current_role() in ('cingshan','dongyuan','admin'));
create policy balances_admin_manage on public.leave_balances for all to authenticated using (public.current_role() in ('cingshan','admin')) with check (public.current_role() in ('cingshan','admin'));
create policy attachments_read_authorized on public.leave_attachments for select to authenticated using (public.can_access_application(application_id));
create policy attachments_insert_owner on public.leave_attachments for insert to authenticated with check (public.can_access_application(application_id));
create policy approvals_read_authorized on public.leave_approvals for select to authenticated using (public.can_access_application(application_id));
create policy approvals_review_insert on public.leave_approvals for insert to authenticated with check (public.can_review_school(school));
create policy routing_read_authorized on public.leave_routing_events for select to authenticated using (public.can_access_application(application_id));
create policy notifications_read_authorized on public.leave_notifications for select to authenticated using (public.can_access_application(application_id));
create policy notifications_insert_authorized on public.leave_notifications for insert to authenticated with check (public.can_access_application(application_id));
create policy line_webhook_events_no_client_access on public.line_webhook_events for all to authenticated using (false) with check (false);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('leave-attachments', 'leave-attachments', false, 10485760, array['application/pdf','image/jpeg','image/png','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/zip'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy leave_storage_read on storage.objects for select to authenticated using (
  bucket_id = 'leave-attachments' and public.can_access_application((split_part(name, '/', 1))::bigint)
);
create policy leave_storage_insert on storage.objects for insert to authenticated with check (
  bucket_id = 'leave-attachments' and public.can_access_application((split_part(name, '/', 1))::bigint)
);
create policy leave_storage_delete on storage.objects for delete to authenticated using (
  bucket_id = 'leave-attachments' and public.current_role() in ('cingshan','admin')
);
