begin;

alter table public.foreign_teacher_leave_applications
  add column if not exists substitute_name text;

create table if not exists public.foreign_teacher_substitutes (
  id bigint generated by default as identity primary key,
  school text not null check (school in ('青山國小', '東原國中')),
  name text not null check (length(trim(name)) > 0),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school, name)
);

alter table public.foreign_teacher_substitutes enable row level security;

create policy substitutes_read_authenticated on public.foreign_teacher_substitutes
  for select to authenticated using (true);

create policy substitutes_school_manage on public.foreign_teacher_substitutes
  for all to authenticated
  using (
    public.foreign_teacher_current_role() = 'admin'
    or (public.foreign_teacher_current_role() = 'cingshan' and school = '青山國小')
    or (public.foreign_teacher_current_role() = 'dongyuan' and school = '東原國中')
  )
  with check (
    public.foreign_teacher_current_role() = 'admin'
    or (public.foreign_teacher_current_role() = 'cingshan' and school = '青山國小')
    or (public.foreign_teacher_current_role() = 'dongyuan' and school = '東原國中')
  );

grant select on public.foreign_teacher_substitutes to authenticated;
grant insert, update, delete on public.foreign_teacher_substitutes to authenticated;

commit;
