-- LINE recipient binding extension. Apply after 202608280001_initial_leave_management.sql.
-- Populate a short-lived binding_code out of band before asking a teacher/admin to send the LINE bind command.

create table if not exists public.foreign_teacher_line_recipient_bindings (
  id bigint generated by default as identity primary key,
  binding_code text not null unique,
  profile_user_id uuid references auth.users(id) on delete cascade,
  school text check (school in ('青山國小', '東原國中')),
  line_user_id text,
  line_group_id text,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  check ((profile_user_id is not null) <> (school is not null))
);

alter table public.foreign_teacher_line_recipient_bindings enable row level security;
create policy line_bindings_no_client_access on public.foreign_teacher_line_recipient_bindings
  for all to authenticated using (false) with check (false);

create index if not exists line_bindings_code_idx on public.foreign_teacher_line_recipient_bindings(binding_code);
create index if not exists line_bindings_school_idx on public.foreign_teacher_line_recipient_bindings(school);
