begin;

create table if not exists public.foreign_teacher_pto_settings (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references auth.users(id) on delete cascade,
  academic_year text not null,
  total_days numeric(8,2) not null check (total_days >= 0),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (teacher_id, academic_year)
);

create index if not exists foreign_teacher_pto_settings_year_idx
  on public.foreign_teacher_pto_settings (academic_year);

alter table public.foreign_teacher_pto_settings enable row level security;

-- Cingshan is the primary school administrator responsible for PTO settings.
drop policy if exists foreign_teacher_profiles_school_read on public.foreign_teacher_profiles;
create policy foreign_teacher_profiles_school_read
  on public.foreign_teacher_profiles
  for select to authenticated
  using (public.foreign_teacher_current_role() in ('cingshan', 'admin'));

drop policy if exists foreign_teacher_pto_settings_read on public.foreign_teacher_pto_settings;
create policy foreign_teacher_pto_settings_read
  on public.foreign_teacher_pto_settings
  for select to authenticated
  using (teacher_id = auth.uid() or public.foreign_teacher_current_role() in ('cingshan', 'admin'));

drop policy if exists foreign_teacher_pto_settings_manage on public.foreign_teacher_pto_settings;
create policy foreign_teacher_pto_settings_manage
  on public.foreign_teacher_pto_settings
  for all to authenticated
  using (public.foreign_teacher_current_role() in ('cingshan', 'admin'))
  with check (public.foreign_teacher_current_role() in ('cingshan', 'admin') and updated_by = auth.uid());

commit;
